"""
TOTP (RFC 6238) helpers for Satori's 2FA flow.

- generate_secret() / verify_code() / provisioning_uri() — standard TOTP plumbing
  via pyotp. Compatible with Google Authenticator, Microsoft Authenticator,
  Authy, 1Password, Bitwarden, etc.
- encrypt_secret() / decrypt_secret() — Fernet symmetric encryption so the
  TOTP shared secret is never stored in plaintext at rest. Key sourced from
  TOTP_ENCRYPTION_KEY (32-byte url-safe base64). If unset, the module
  derives a deterministic key from JWT_SECRET as a dev fallback so local
  development doesn't require a separate secret — but you SHOULD set
  TOTP_ENCRYPTION_KEY for production (the deploy script provisions it).
- generate_backup_codes() — 10 single-use recovery codes shown to the user
  once at enrollment. Codes are bcrypt-hashed before storage (same crypto
  as the password column).
- qr_png_data_url() — produces an inline `data:image/png;base64,...` PNG
  the frontend can drop straight into an <img src>.
"""
import os
import io
import base64
import hashlib
import secrets

import pyotp
import qrcode
import bcrypt as _bcrypt
from cryptography.fernet import Fernet


# ── Encryption key for the TOTP secret at rest ──────────────────────────

def _fernet() -> Fernet:
    """Return a Fernet instance keyed by TOTP_ENCRYPTION_KEY.

    If the env var is unset we DETERMINISTICALLY derive a key from
    JWT_SECRET — keeps local dev frictionless. Production should set
    TOTP_ENCRYPTION_KEY to a value generated by `Fernet.generate_key()`.
    """
    key_env = os.environ.get("TOTP_ENCRYPTION_KEY", "").strip()
    if key_env:
        return Fernet(key_env.encode())
    # Dev fallback — derive from JWT_SECRET so the key is stable across restarts
    seed = os.environ.get("JWT_SECRET", "satori-secret-key-change-in-production")
    digest = hashlib.sha256(seed.encode()).digest()
    return Fernet(base64.urlsafe_b64encode(digest))


def encrypt_secret(secret: str) -> str:
    return _fernet().encrypt(secret.encode()).decode()


def decrypt_secret(encrypted: str) -> str:
    return _fernet().decrypt(encrypted.encode()).decode()


# ── TOTP plumbing ───────────────────────────────────────────────────────

def generate_secret() -> str:
    """Return a fresh base32 secret (32 chars, ~160 bits)."""
    return pyotp.random_base32()


def verify_code(secret: str, code: str, window: int = 1) -> bool:
    """Verify a 6-digit TOTP. window=1 accepts the previous + current + next
    30-second slot (±30s tolerance) to handle clock drift on the user's phone.
    Returns False on missing/malformed input rather than raising."""
    if not secret or not code:
        return False
    code = "".join(ch for ch in code if ch.isdigit())
    if len(code) != 6:
        return False
    try:
        return pyotp.TOTP(secret).verify(code, valid_window=window)
    except Exception:
        return False


def provisioning_uri(secret: str, account: str, issuer: str = "Satori TMC") -> str:
    """otpauth://totp/ URI the Authenticator app encodes into the QR."""
    return pyotp.TOTP(secret).provisioning_uri(name=account, issuer_name=issuer)


def qr_png_data_url(uri: str) -> str:
    """Render the provisioning URI as a PNG, return data: URL for inline <img>."""
    img = qrcode.make(uri)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    b64 = base64.b64encode(buf.getvalue()).decode()
    return f"data:image/png;base64,{b64}"


# ── Backup / recovery codes ─────────────────────────────────────────────

def generate_backup_codes(n: int = 10) -> list[str]:
    """Return `n` human-typable recovery codes in the form `XXXX-XXXX`
    (8 base32-ish chars, dashed for readability). Each is unique and
    pulls 40 bits of entropy from secrets.token_hex.
    """
    alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"  # no 0/O/1/I/L
    out = []
    seen = set()
    while len(out) < n:
        raw = "".join(secrets.choice(alphabet) for _ in range(8))
        code = f"{raw[:4]}-{raw[4:]}"
        if code in seen:
            continue
        seen.add(code)
        out.append(code)
    return out


def hash_backup_code(code: str) -> str:
    """bcrypt-hash a backup code so the plaintext doesn't sit in the DB."""
    # Normalize: case-insensitive + strip dashes/spaces.
    norm = "".join(ch for ch in code.upper() if ch.isalnum())
    return _bcrypt.hashpw(norm.encode(), _bcrypt.gensalt()).decode()


def check_backup_code(code: str, hashed: str) -> bool:
    norm = "".join(ch for ch in (code or "").upper() if ch.isalnum())
    try:
        return _bcrypt.checkpw(norm.encode(), hashed.encode())
    except Exception:
        return False
